export const ON_PREFERENCES_CHANGED = "ON_PREFERENCES_CHANGED";
export const UPDATE_PROFILE_PREFERENCES_REQUEST =
  "UPDATE_PROFILE_PREFERENCES_REQUEST";
export const UPDATE_PROFILE_PREFERENCES_SUCCESS =
  "UPDATE_PROFILE_PREFERENCES_SUCCESS";
export const UPDATE_PROFILE_PREFERENCES_FAILURE =
  "UPDATE_PROFILE_PREFERENCES_FAILURE";
