export const UPDATE_PROFILE_FAVORITE_REQUEST =
  "UPDATE_PROFILE_FAVORITE_REQUEST";
export const UPDATE_PROFILE_FAVORITE_SUCCESS =
  "UPDATE_PROFILE_FAVORITE_SUCCESS";
export const UPDATE_PROFILE_FAVORITE_FAILURE =
  "UPDATE_PROFILE_FAVORITE_FAILURE";
