export const GET_RECIPES_REQUEST = "GET_RECIPES_REQUEST";
export const GET_RECIPES_SUCCESS = "GET_RECIPES_SUCCESS";
export const GET_RECIPES_FAILURE = "GET_RECIPES_FAILURE";
export const GENERATE_RECIPES_REQUEST = "GENERATE_RECIPES_REQUEST";
export const GENERATE_RECIPES_SUCCESS = "GENERATE_RECIPES_SUCCESS";
export const GENERATE_RECIPES_FAILURE = "GENERATE_RECIPES_FAILURE";
